series: Basic C++
title: Overloading
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: If used correctly, function overloads can make your code simpler and easier to read.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Constructors and Destructors